### ISSUE TITLE
code_gen omits docstrings on Python 3.7

### ISSUE THREAD

**Issue by Kodiologist** [berkerpeksag/astor#101]
$ python -c 'import ast, astor; print(astor.code_gen.to_source(ast.Module(body = [ast.parse("def f():\n \"docstring\"\n 1")])) )'
    def f():
        1

    $ python -c 'import ast, astor; print(astor.code_gen.to_source(ast.Module(body = [ast.parse("class C:\n \"docstring\"\n 1")])) )'
    class C:
        1

    $ python -c 'import ast, astor; print(astor.code_gen.to_source(ast.Module(body = [ast.parse("\"hello\"\n1")])))' 
    1

**Comment by berkerpeksag** [comment]
I assume the cause of this is the new `node.docstring` attribute in 3.7?

**Comment by Kodiologist** [comment]
That seems like a good bet.
