### ISSUE TITLE
Remove check for node.docstring

### ISSUE THREAD

**Issue by berkerpeksag** [berkerpeksag/astor#106]
`node.docstring` has just removed from 3.7.0.b5 due to backwards compatibility reasons. See https://github.com/python/cpython/pull/7121/ for details.

By looking at the pull request, reverting https://github.com/berkerpeksag/astor/commit/524d525e999f98198787bb35d0b18d83cfa25d4a might be enough.

@radomirbosak would you like to submit a pull request?

**Comment by berkerpeksag** [comment]
We should, of course, still keep the tests and changes in `.travis.yml`.

**Comment by Kodiologist** [comment]
Beware that [only old alphas of Python 3.7 are currently available on Travis](https://docs.travis-ci.com/user/languages/python/#Development-releases-support).

**Comment by berkerpeksag** [comment]
Thanks for the heads up. The whole docstring situation is a complete mess...
