### ISSUE TITLE
code_gen represents an empty set as an empty dictionary

### ISSUE THREAD

**Issue by Kodiologist** [berkerpeksag/astor#108]
python -c 'import ast, astor; print(astor.code_gen.to_source(ast.Set([])))'
    {}

Since Python has no literal syntax for the empty set, and we can't use `set()` because the name `set` might be rebound, I think the right representation is `{1}.__class__()`.

**Comment by berkerpeksag** [comment]
Sounds good to me. Would you like to submit a PR?

**Comment by berkerpeksag** [comment]
@Kodiologist thank you very much, I will convert it to a pull request!
