### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by Kodiologist** [berkerpeksag/astor#111]
I'd like to make a new Hy release soon (before August), and Hy now depends on new features and bug fixes in astor, particularly for Python 3.7 compatibility.

**Comment by berkerpeksag** [comment]
I will review open PRs this week and hopefully release 0.7 this weekend.

**Comment by Kodiologist** [comment]
Cool, thank you.

**Comment by mbarkhau** [comment]
Just ran into this. 

```
E     File "/home/username/miniconda3/envs/env37/lib/python3.7/site-packages/astor/code_gen.py", line 311
E       def visit_FunctionDef(self, node, async=False):
E                                             ^
E   SyntaxError: invalid syntax
```

Looking forward to the release.

**Comment by berkerpeksag** [comment]
Thanks for the heads up. There are a few open PRs I'd like to get in for 0.7, so I'm going to release it this weekend.

**Comment by berkerpeksag** [comment]
0.7 is now up! https://pypi.org/project/astor/0.7.0/

**Comment by Kodiologist** [comment]
Great, I'll get the ball rolling for Hy 0.15.
