### ISSUE TITLE
PyPI package for 0.7.0 does not contain setuputils.py

### ISSUE THREAD

**Issue by moubctez** [berkerpeksag/astor#116]
PyPI package for 0.7.0 does not contain `setuputils.py` and building fails with
```
  File "setup.py", line 5, in <module>
    from setuputils import find_version
ModuleNotFoundError: No module named 'setuputils'
```
Please, fix. :)

**Comment by berkerpeksag** [comment]
Bah, sorry for the noise! I'm about to release 0.7.1, can you test it on Test PyPI?

```sh
$ pip install -i https://test.pypi.org/simple/ astor
```

**Comment by berkerpeksag** [comment]
0.7.1 released on PyPI. Could you try installing 0.7.1 from PyPI, not Test PyPI?

**Comment by moubctez** [comment]
This one is better. Thanks! :) 👍

**Comment by berkerpeksag** [comment]
No problem, and thank you for the report! :)
