### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by Kodiologist** [berkerpeksag/astor#144]
Once again, Hy is relying on unreleased astor features in order to support bleeding-edge Python. Could you release a new astor so we can release a new Hy?

**Comment by berkerpeksag** [comment]
Of course! I'm going to release 0.8.0 tonight.

**Comment by berkerpeksag** [comment]
Done: https://pypi.org/project/astor/0.8.0/

**Comment by Kodiologist** [comment]
Danke!
