### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jackiezhang11** [berkerpeksag/astor#214]
python 3.7
ubuntu18.04

 astor vesion:0.6.2
astor/code_gen.py line 311
def visit_FunctionDef(self, node, async=False):
prefix = 'async ' if async else '

SyntaxError: invalid syntax

**Comment by berkerpeksag** [comment]
Thank you for your report. This has already been fixed in https://github.com/berkerpeksag/astor/commit/fe1ef7f9d746847c157197e4cb2ab6505fe19faf and it has been available since version 0.7. Please upgrade astor to at least 0.7.

**Comment by jackiezhang11** [comment]
thank you
