### ISSUE TITLE
Deprecate old API

### ISSUE THREAD

**Issue by berkerpeksag** [berkerpeksag/astor#36]
- https://github.com/berkerpeksag/astor/commit/c479d88d936cf7f18db42c3c839d0433edad2f0c
- https://github.com/berkerpeksag/astor/commit/12cdde633bb3a498b04753b1ccb0ae7c146c8f9d

**Comment by leonardt** [comment]
From https://github.com/berkerpeksag/astor/commit/c479d88d936cf7f18db42c3c839d0433edad2f0c

It looks like these are the API changes
```python
get_boolop = get_binop = get_cmpop = get_unaryop =  get_op_symbol # NOQA
get_anyop = get_op_symbol
parsefile = code_to_ast.parse_file
codetoast = code_to_ast
dump = dump_tree
all_symbols = symbol_data
treewalk = tree_walk
codegen = code_gen 
```

Anything missing?

And deprecation strategy?
* Could wrap those deprecated functions to print out a warning that in the next release (0.7) these functions will be removed
* Just remove them for 0.6

Either strategy will require an update to the docs. I'd be happy to do that once the above are addressed.

**Comment by pmaupin** [comment]
I think a warning would be great.

Thanks,
Pat

**Comment by pmaupin** [comment]
I've checked code to do the deprecation, @leonardt 

If you could look at the doc issue (as well as the separate change log sphinx issue) that would be awesome.

Thanks,
Pat

**Comment by berkerpeksag** [comment]
Thanks, @leonardt. We'll probably keep the old names until we release 1.0. So,

1. Show warnings for deprecated names
2. Document deprecated names with `.. deprecated:: 0.6`

sounds like a good plan to me.

**Comment by pmaupin** [comment]
Speaking of cluttering up the doc -- if we've never had documentation for these, should we bother adding them to the doc?

FWIW, I think the code's done.  The test looks solid.

**Comment by berkerpeksag** [comment]
I've seen some weird usages of the current undocumented API so I guess adding something like "these things are deprecated in 0.6" to docs wouldn't hurt :)
