### ISSUE TITLE
python setup.py install does not install into anaconda

### ISSUE THREAD

**Issue by pmaupin** [berkerpeksag/astor#43]
Not sure why and no time to debug right now.

sudo python setup.py install will appear to _work_ under anaconda, but will install into system python directories.

All that setup stuff is a complete mystery to me.

**Comment by berkerpeksag** [comment]
`python` is probably linked to the system Python. Perhaps something like `conda install your/astor/directory/` would work?

**Comment by pmaupin** [comment]
Cannot reproduce ATM; closing
