### ISSUE TITLE
Print out elif statements

### ISSUE THREAD

**Issue by kirbyfan64** [berkerpeksag/astor#45]
See https://github.com/hylang/hy/pull/824#issuecomment-121435597 for more info.

**Comment by pmaupin** [comment]
@kirbyfan64 -- PR #46 adds a working test for elif.  Since it's a valid test and this question might come up in the future, we should probably just go ahead and add it to the master branch.

Unless you can add a counter-example test that shows a failure, please close this issue.

Thanks,
Pat

**Comment by kirbyfan64** [comment]
@pmaupin Ah, my bad. Slight brain failure. :O Sorry for the trouble!
