### ISSUE TITLE
Calls that aren't part of anything in the body of a FunctionDef don't get a new line.

### ISSUE THREAD

**Issue by vincelugli** [berkerpeksag/astor#47]
When creating a ```FunctionDef``` ast, if you have a ```Call``` as part of the body, the ```Call``` will not be on a new line.

```
def foo():
    bar()
```
will appear as 
```
def foo():bar()
```

**Comment by vincelugli** [comment]
Call needs to be wrapped in an expression, sorry for the spam!

**Comment by berkerpeksag** [comment]
No problem, I'm glad you solved it :)
