### ISSUE TITLE
Document public API

### ISSUE THREAD

**Issue by berkerpeksag** [berkerpeksag/astor#5]
- astor.codegen
- astor.treewalk
- astor.misc

**Comment by pmaupin** [comment]
I believe the doc at readthedocs qualifies, no?

**Comment by berkerpeksag** [comment]
Yeah, we have initial docs at RtD, but we still need to document the whole public API.

**Comment by pmaupin** [comment]
Fair enough.

**Comment by berkerpeksag** [comment]
I think this is now done. We can handle further documentation requests in separate issues.
