### ISSUE TITLE
Please release a new version to PyPI

### ISSUE THREAD

**Issue by ulope** [berkerpeksag/astor#53]
The last release on PyPI is from 2015-04-18. There have been quite a lot of commits since then. It would be great not having to install directly from Github.

**Comment by berkerpeksag** [comment]
Thanks for the ping! A new release is on my TODO list, but we've changed a lot of code and we need to properly document/deprecate them before doing a new release. See #36 and #37.

**Comment by ztane** [comment]
BTW is there support for Python 3.6 yet?

**Comment by berkerpeksag** [comment]
Not really, I haven't had a chance to run the tests on Python 3.6 yet.

**Comment by pmaupin** [comment]
There's a 3.6???

Wow, you learn something new every week. :)

Uhh, but seriously, I've been preoccupied and had no idea there was a new Python out.  Now I have to go look at all the goodies.

**Comment by ztane** [comment]
@pmaupin not yet, but it's got some new interesting syntax, coming out in December, including the format strings and variable annotations, that I'd very much like to see supported.

**Comment by zackmdavis** [comment]
(A few months ago, I [started working on](https://github.com/zackmdavis/astor/commit/141a334c68) codegen visitors for the new [PEP 498](https://www.python.org/dev/peps/pep-0498/) AST nodes, but didn't finish; if someone is especially eager to take over, they're welcome to, otherwise I'll probably get to it sometime.)

**Comment by alexbw** [comment]
+1

**Comment by zackmdavis** [comment]
> (A few months ago, I started

(quietly happy that @kirbyfan64 has scooped me on f-strings; looking at his implementation, it looks more complicated than I was expecting)

**Comment by samuelcolvin** [comment]
I was really excited to find this project with recent commits for 3.6 features, but a bit depressed to find the most recent release was so old and didn't work at all with 3.5 or 3.6.

It would be great if you could release a new version. It doesn't have to be perfect: master@HEAD is already way better than the released version (eg. it works at all with python released in the last 3 years!).

Anyone relying on 0.5 can continue to use that, I really don't see how a new release can hurt.

If you're waiting for "perfect" it'll never come - move fast and break things.

**Comment by Suor** [comment]
This also blocks me from releasing to PyPI. How about releasing 0.6.beta or something?

**Comment by berkerpeksag** [comment]
Doing a release without a compatibility shim and documentation updates would be a disaster for our existing users (e.g. Hylang) I'm going to try to release 0.6 next week.

Thank you for all pings!

**Comment by alexbw** [comment]
Any updates? Really looking forward to a fresh release cut!

**Comment by berkerpeksag** [comment]
I've started to work on 0.7 release so hopefully it will be released by the end of the week.

**Comment by berkerpeksag** [comment]
I've just released astor 0.6. Thank you all for your support. Hopefully, 0.6 won't break any code :)
