### ISSUE TITLE
Make changelog look better at readthedocs

### ISSUE THREAD

**Issue by pmaupin** [berkerpeksag/astor#65]
Someone who knows sphinx better than me (e.g. at all) should look into this.

changelog.rst will have to be modified.

Look at modifications to index.rst to see how to make it still display properly at github.

**Comment by berkerpeksag** [comment]
We really shouldn't support reading any docs on GitHub. It's broken, unsupported and astor isn't the only project that suffers from it. We already put the RtD link in README and project description so IMO that should be enough.

**Comment by pmaupin** [comment]
How about at least the note at the top that says you're not seeing everything?  (It only shows up at github; doesn't clutter the doc at rtfd.)

**Comment by berkerpeksag** [comment]
> How about at least the note at the top that says you're not seeing everything?

Sounds good to me!

**Comment by berkerpeksag** [comment]
Fixed in https://github.com/berkerpeksag/astor/commit/b1d4476fabb421ccd89dc808fb41dcade46d13bb.
