### ISSUE TITLE
imoprt astor fails with ModuleNotFound

### ISSUE THREAD

**Issue by all3fox** [berkerpeksag/astor#81]
I have installed the `0.5` version of `astor` with `pip install astor`, I can see it in my virtual environement when I do `pip list`. However, if I try to `import astor` then `ModuleNotFound` is thrown. What am I doing wrong?

**Comment by all3fox** [comment]
Apologies, looks like an issue with my virtual environment setup. It worked with `3.6.1` under `pyenv virtualenv` after I wiped/reinstalled all of the virtual environments. Closing.

**Comment by all3fox** [comment]
Correction: I am observing that when my repl is vanilla `python` or `ipython` then `import astor` works. However, if I use `bpython` as my repl, the import fails with `ModuleNotFoundError`. Probably an issue with `bpython`.

**Comment by berkerpeksag** [comment]
Thank you for the report and follow-up!
