### ISSUE TITLE
Can't generate code containing ast.Num(NaN)

### ISSUE THREAD

**Issue by Kodiologist** [berkerpeksag/astor#85]
Somewhat related to #82, the `codegen` of astor 0.5 would produce `nan` if given a `Num` node that contained NaN. In astor 0.6, the following raises an `AssertionError` in code_gen.py:

```py
import ast, astor

nan = 1e1000 - 1e1000

print(astor.code_gen.to_source(
         ast.Module([ast.Expr(ast.BinOp(
             ast.Num(1.0),
             ast.Add(),
             ast.Num(nan)))])))
```

While Python has no NaN literal, you could represent `ast.Num(nan)` as an expression (such as `1e1000 - 1e1000`) if you want to generate real Python. See hylang/hy#1447.

**Comment by pmaupin** [comment]
We can add this, but of course, it won't round-trip AST -> Python -> AST properly.

**Comment by berkerpeksag** [comment]
@Kodiologist I'm planning to release 0.7.0 this weekend and I can merge a fix for this if you still need it for Hy.

**Comment by Kodiologist** [comment]
It would be convenient, but it's not necessary. I worked around the issue in Hy commit a074bb9a5c3 by replacing NaN with such expressions in the compiler.
