### ISSUE TITLE
'async' and 'await' will become keywords in Python 3.7

### ISSUE THREAD

**Issue by berkerpeksag** [berkerpeksag/astor#86]
The following code won't work in Python 3.7:

https://github.com/berkerpeksag/astor/blob/5f189fc5cae9a5c3ca75bc204a8ac9a361b4bcc7/astor/code_gen.py#L311

Full list:

```
astor/code_gen.py:311:    def visit_FunctionDef(self, node, async=False):
astor/code_gen.py:312:        prefix = 'async ' if async else ''
astor/code_gen.py:325:        self.visit_FunctionDef(node, async=True)
astor/code_gen.py:367:    def visit_For(self, node, async=False):
astor/code_gen.py:369:        prefix = 'async ' if async else ''
astor/code_gen.py:376:        self.visit_For(node, async=True)
astor/code_gen.py:383:    def visit_With(self, node, async=False):
astor/code_gen.py:384:        prefix = 'async ' if async else ''
astor/code_gen.py:395:        self.visit_With(node, async=True)
```

**Comment by vodik** [comment]
Do you have a particular solution in mind? Or am I free to adjust this? I don't image its technically part of your public API.

**Comment by berkerpeksag** [comment]
I'm planning to rename `async` to `is_async`. Would you like to submit a PR?

**Comment by berkerpeksag** [comment]
Also, I wonder if we can drop the `async` keyword argument and replace

```py
prefix = 'async ' if async else ''
```

with

```py
prefix = 'async ' if self.get_is_async(node) else ''
```

in `visit_FunctionDef`.

**Comment by vodik** [comment]
Yeah, sure, I can do that.

**Comment by zackmdavis** [comment]
(Sorry, I should have foreseen that this was going to be a problem in #19)
