### ISSUE TITLE
Incorrect result for tuple expansion

### ISSUE THREAD

**Issue by ryanorendorff** [berkerpeksag/astor#92]
Hello,

There seems to be an error turning an ast back into the correct form when expanding tuples. For example, take the following code.

```
a = (1, 2)
b = (*a, 3)
```

Running `rtrip` on this code fragment leads to the following

```
a = 1, 2
b = *a, 3
```

which unfortunately is not valid python.

**Comment by berkerpeksag** [comment]
Thank you for your report. This is indeed a bug. Would you like to submit a PR?

**Comment by berkerpeksag** [comment]
Good catch, @radomirbosak, thank you!

@ryanorendorff I'm going to close this for now, but we can always reopen if you have time to give us a little bit more information to understand the issue.
